# Generated by Django 4.2.7 on 2023-11-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mipagina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
